- name: create temporary directory
  always_run: yes
  shell: mktemp -d
  register: tempdir

- name: temporarly store cleartext admin rootpw
  copy: dest={{ tempdir.stdout }}/admin-georchestra.pass content={{ openldap.rootpw }} mode=0400

- name: purge DIT
  ignore_errors: yes
  command: ldapdelete -D {{ openldap.rootdn }} -x -y {{ tempdir.stdout }}/admin-georchestra.pass -r "{{ openldap.basedn }}"

- name: recursively purge temp dir
  file: dest={{ tempdir.stdout }} state=absent

- name: remove cn=config bits
  file: dest=/etc/ldap/slapd.d/cn=config/{{ item }} state=absent
  with_items:
  - "olcDatabase={2}mdb.ldif"
  - "cn=schema/cn={4}groupofmembers.ldif"
  notify: restart slapd

#XX remove /var/lib/ldap ?
