- name: remove apache directories/config
  file: name={{ item }} state=absent
  with_items:
  - /etc/apache2/sites-enabled/georchestra.conf
  - /etc/apache2/sites-available/georchestra.conf
  - /var/www/georchestra/
  notify: reload apache2

#XXX disable unneeded modules/reenable default site ?
