- name: checkout georchestra datadir
  git:
    dest: "{{ georchestra.datadir.path }}"
    repo: "{{ georchestra.datadir.gitrepo }}"
    version: "{{ georchestra.datadir.gitversion }}"
    force: yes

- name: create cadastrapp subdir
  always_run: yes
  file: path="{{ georchestra.datadir.path }}/cadastrapp" state=directory

- name: template config files
  template:
    src: "{{ item.war }}/{{ item.file }}.j2"
    dest: "{{ georchestra.datadir.path }}/{{ item.war }}/{{ item.destdir }}/{{ item.file }}"
    backup: yes
#  debug: var=item
  with_items:
  - { file: targets-mapping.properties, war: security-proxy, destdir: '' }
  - { file: security-proxy.properties, war: security-proxy , destdir: '' }
  - { file: trusted-users.properties, war: security-proxy , destdir: '' }
  - { file: log4j.properties, war: security-proxy, destdir: 'log4j' }
  - { file: cas.properties, war: cas, destdir: '' }
  - { file: log4j.xml, war: cas, destdir: 'log4j' }
  - { file: ldapadmin.properties, war: ldapadmin, destdir: '' }
  - { file: log4j.properties, war: ldapadmin, destdir: 'log4j' }
  - { file: log4j.properties, war: geowebcache, destdir: 'log4j' }
  - { file: geowebcache.properties, war: geowebcache, destdir: '' }
  - { file: log4j.xml, war: geonetwork, destdir: 'log4j' }
  - { file: geonetwork.properties, war: geonetwork, destdir: '' }
#  - { file: geofence-geoserver.properties, war: geoserver, destdir: 'WEB-INF/classes' }
  - { file: credentials.properties, war: mapfishapp, destdir: '' }
  - { file: config.yaml, war: mapfishapp, destdir: 'print' }
  - { file: log4j.properties, war: mapfishapp, destdir: 'log4j' }
  - { file: GEOR_custom.js, war: mapfishapp, destdir: 'js' }
  - { file: log4j.properties, war: extractorapp, destdir: 'log4j' }
  - { file: extractorapp.properties, war: extractorapp, destdir: '' }
#  - { file: log4j.properties, war: downloadform, destdir: 'WEB-INF/classes' }
#  - { file: downloadform.properties, war: downloadform, destdir: 'WEB-INF' }
  - { file: log4j.properties, war: analytics, destdir: 'log4j' }
  - { file: analytics.properties, war: analytics, destdir: '' }
  - { file: GEOR_custom.js, war: analytics, destdir: 'js' }
  - { file: cadastrapp.properties, war: cadastrapp, destdir: '' }
  - { file: logback.xml, war: cadastrapp, destdir: '' }
  notify: restart all tomcats
