other_schemas: [ mapfishapp, ldapadmin, downloadform, geofence, ogcstatistics ]
other_schemas_urls:
  - https://raw.github.com/georchestra/georchestra/master/postgresql/02-mapfishapp.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/04-ldapadmin.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/03-downloadform.sql
  - https://raw.github.com/georchestra/geofence/georchestra/doc/setup/sql/002_create_schema_postgres.sql
  - https://raw.github.com/georchestra/georchestra/master/postgresql/05-ogc-server-statistics.sql
cadastrappsql: {
  tmpdir: /tmp/cadastrapp/sql,
  views : [
    { script: qgisCommune, view: commune },
    { script: qgisHabitationDetails, view: deschabitation },
    { script: qgisParcelle, view: parcelle },
    { script: qgisProprietaire, view: proprietaire },
    { script: qgisProprietaireParcelle, view: proprietaire_parcelle },
    { script: qgisCoProprieteParcelle, view: co_propriete_parcelle },
    { script: qgisProprieteBatie, view: proprietebatie },
    { script: qgisProprieteNonBatie, view: proprietenonbatie },
    { script: qgisProprieteNonBatieSufExo, view: proprietenonbatiesufexo },
    { script: qgisSection, view: section } ],
  tables: [
    { script: groupe_autorisation, path: commun/user },
    { script: uf_parcelle, path: qgis/tables },
    { script: request_information, path: commun/tables },
    { script: prop_ccodem, path: commun/tables },
    { script: prop_ccodro, path: commun/tables },
    { script: prop_ccoqua, path: commun/tables },
    { script: prop_ccogrm, path: commun/tables },
    { script: prop_dmatgm, path: commun/tables },
    { script: prop_dmatto, path: commun/tables },
    { script: prop_dnatpr, path: commun/tables } ],
  indexes: [ { script: index, index: idxcommunelibcom } ]
}
